/**
 * ============================================================================
 *  DEMO DATA — NOT OFFICIAL STATISTICS
 * ============================================================================
 *  Synthetic incident records generated by a seeded pseudo-random generator so
 *  the prototype's KPIs, charts, map and table respond realistically to
 *  filters. They do not describe real events or people and must never be
 *  cited. Records contain no names, addresses or other personal data.
 *
 *  `TEMPLATE_RECORDS` are hand-written examples; the rest of the dataset is
 *  generated around them. Replace `DEMO_INCIDENTS` to connect a real dataset.
 * ============================================================================
 */
import type { AgeGroup, Incident, RecordStatus, RegionId, Source, Verification, VictimGroup, ViolenceType } from '../types'
import { todayISO } from '../utils/date'

export const CONFLICT_START = '2022-02-24'
export const TOTAL_REGIONS = 26

/** Hand-written demo records (also used as the first rows of the dataset). */
// prettier-ignore
const TEMPLATE_RECORDS: Omit<Incident, 'id'>[] = [
  { date: '2024-03-12', region: 'kharkiv',      type: 'sexual',        victimGroup: 'adult',    ageGroup: '25-34',    source: 'un-report',     verification: 'corroborated', status: 'documented' },
  { date: '2022-03-18', region: 'kyiv',         type: 'physical',      victimGroup: 'adult',    ageGroup: '45-54',    source: 'un-report',     verification: 'verified',     status: 'documented' },
  { date: '2022-04-02', region: 'chernihiv',    type: 'detention',     victimGroup: 'adult',    ageGroup: null,       source: 'ngo-report',    verification: 'verified',     status: 'referred' },
  { date: '2022-11-14', region: 'kherson',      type: 'sexual',        victimGroup: 'adult',    ageGroup: '18-24',    source: 'un-report',     verification: 'verified',     status: 'referred' },
  { date: '2023-06-08', region: 'lviv',         type: 'displacement',  victimGroup: 'under-18', ageGroup: 'under-18', source: 'ngo-report',    verification: 'reported',     status: 'documented' },
  { date: '2025-02-17', region: 'donetsk',      type: 'psychological', victimGroup: 'older',    ageGroup: '55+',      source: 'health-facility', verification: 'reported',   status: 'under-review' },
]

type Weighted<T> = readonly (readonly [T, number])[]

function mulberry32(seed: number) {
  let a = seed
  return () => {
    a = (a + 0x6d2b79f5) | 0
    let t = Math.imul(a ^ (a >>> 15), 1 | a)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

const rand = mulberry32(20220224)

function pick<T>(items: Weighted<T>): T {
  const total = items.reduce((s, [, w]) => s + w, 0)
  let r = rand() * total
  for (const [item, w] of items) {
    r -= w
    if (r <= 0) return item
  }
  return items[items.length - 1][0]
}

// Two regions intentionally have no records, so the dataset covers 24 of 26.
const REGION_WEIGHTS: Weighted<RegionId> = [
  ['donetsk', 14],
  ['kharkiv', 12],
  ['kherson', 11],
  ['zaporizhzhia', 10],
  ['luhansk', 8],
  ['kyiv', 7],
  ['mykolaiv', 5],
  ['chernihiv', 5],
  ['sumy', 4],
  ['dnipropetrovsk', 4],
  ['odesa', 3],
  ['crimea', 3],
  ['kyiv-city', 2.5],
  ['lviv', 2.5],
  ['zhytomyr', 1.5],
  ['poltava', 1.2],
  ['vinnytsia', 1],
  ['zakarpattia', 0.8],
  ['cherkasy', 0.7],
  ['kirovohrad', 0.6],
  ['ivano-frankivsk', 0.6],
  ['chernivtsi', 0.5],
  ['rivne', 0.4],
  ['volyn', 0.4],
]

const TYPE_WEIGHTS: Weighted<ViolenceType> = [
  ['sexual', 26.5],
  ['physical', 22],
  ['psychological', 17],
  ['displacement', 16],
  ['detention', 11],
  ['other', 7.5],
]
const GROUP_WEIGHTS: Weighted<VictimGroup> = [
  ['adult', 74],
  ['under-18', 15],
  ['older', 11],
]
const ADULT_AGES: Weighted<AgeGroup> = [
  ['18-24', 19],
  ['25-34', 30],
  ['35-44', 26],
  ['45-54', 17],
  ['55+', 8],
]
const SOURCE_WEIGHTS: Weighted<Source> = [
  ['un-report', 24],
  ['ngo-report', 30],
  ['government', 22],
  ['health-facility', 14],
  ['media-verified', 10],
]

/** Relative monthly volume: early peak, plateau, slight recent decline. */
function monthWeight(index: number): number {
  const early = [0.5, 3.2, 2.6, 2.0, 1.6][index]
  if (early) return early
  return 1.05 + 0.18 * Math.sin(index / 3.2) - index * 0.006
}

function verificationFor(monthsAgo: number): Verification {
  const maturity = Math.min(1, monthsAgo / 18) // older records have had time to be verified
  return pick<Verification>([
    ['verified', 10 + 26 * maturity],
    ['corroborated', 20 + 14 * maturity],
    ['reported', 42 - 16 * maturity],
    ['unverified', 28 - 22 * maturity],
  ])
}

function statusFor(v: Verification): RecordStatus {
  if (v === 'unverified') return 'under-review'
  if (v === 'verified')
    return pick<RecordStatus>([
      ['documented', 6],
      ['referred', 4],
    ])
  return pick<RecordStatus>([
    ['documented', 8],
    ['under-review', 2],
    ['referred', 1],
  ])
}

const TARGET_TOTAL = 12_847

function generate(): Incident[] {
  const end = todayISO()
  const [endY, endM] = end.split('-').map(Number)
  const months: { y: number; m: number }[] = []
  for (let y = 2022, m = 2; y < endY || (y === endY && m <= endM); m === 12 ? ((m = 1), y++) : m++) months.push({ y, m })
  const weights = months.map((_, i) => monthWeight(i))
  const weightSum = weights.reduce((a, b) => a + b, 0)
  const generatedTotal = TARGET_TOTAL - TEMPLATE_RECORDS.length

  const out: Omit<Incident, 'id'>[] = [...TEMPLATE_RECORDS]
  let assigned = 0
  months.forEach(({ y, m }, i) => {
    const isLast = i === months.length - 1
    const count = isLast ? generatedTotal - assigned : Math.round((weights[i] / weightSum) * generatedTotal)
    assigned += count
    const firstDay = i === 0 ? 24 : 1
    const lastDay = isLast ? Number(end.slice(8, 10)) : new Date(Date.UTC(y, m, 0)).getUTCDate()
    for (let k = 0; k < count; k++) {
      const day = firstDay + Math.floor(rand() * (lastDay - firstDay + 1))
      const victimGroup = pick(GROUP_WEIGHTS)
      const knownAge = rand() < 0.62 // age information exists only for a subset
      const ageGroup: AgeGroup | null = !knownAge
        ? null
        : victimGroup === 'under-18'
          ? 'under-18'
          : victimGroup === 'older'
            ? '55+'
            : pick(ADULT_AGES)
      const verification = verificationFor(months.length - 1 - i)
      out.push({
        date: `${y}-${String(m).padStart(2, '0')}-${String(day).padStart(2, '0')}`,
        region: pick(REGION_WEIGHTS),
        type: pick(TYPE_WEIGHTS),
        victimGroup,
        ageGroup,
        source: pick(SOURCE_WEIGHTS),
        verification,
        status: statusFor(verification),
      })
    }
  })

  return out
    .sort((a, b) => a.date.localeCompare(b.date))
    .map((r, i) => ({ ...r, id: `UA-${String(i + 1).padStart(5, '0')}` }))
    .reverse()
}

/** DEMO DATA — synthetic records, newest first. */
export const DEMO_INCIDENTS: Incident[] = generate()
